#!/bin/bash

############################
#			   #
# Made by Tiphaine LAURENT #
#			   #
############################

if [[ -z $1 ]]; then
    echo "Usage: archive <file|dir>"
    exit 1
fi

dir=$(dirname $1)
name="."$(basename $1)".old"

echo "Compressing $1 into $name at $dir"
tar -czf $dir"/"$name".tar" $1
rm -rf $1
