#!/bin/bash

########### CONSTANT VARIABLES ###########

BITS32="i686"
BITS64="x86_64"

SRC_DIR="src"

##########################################

add_libmy()
{
    echo "Does your Makefile needs your EPITECH library ? : [o/n]"
    read libmy
    echo
    local libmy=${libmy,,}

    if [[ $libmy == "o" ]] || [[ $libmy == "oui" ]] ||
	   [[ $libmy == "y" ]] || [[ $libmy == "yes" ]];
    then
	echo -e "LDFLAGS\t\t=\t-lmy -Llibs_srcs" >> Makefile
	lib="on"
    fi
}

add_libmath()
{
    echo "Does your Makefile needs the math lib ? : [o/n]"
    read libm
    echo
    local libm=${libm,,}

    if [[ $libm == "o" ]] || [[ $libm == "oui" ]] ||
	   [[ $libm == "y" ]] || [[ $libm == "yes" ]];
    then
	if [[ $lib == "on" ]];
	then
	    echo -e "LDFLAGS\t\t+=\t-lm" >> Makefile
	else
	    echo -e "LDFLAGS\t\t=\t-lm" >> Makefile
	fi
	lib="on"
    fi
}

add_libcsfml()
{
    echo "Does your Makefile needs the CSFML lib ? : [o/n]"
    read libcsfml
    echo
    local libcsfml=${libcsfml,,}

    if [[ $libcsfml == "o" ]] || [[ $libcsfml == "oui" ]] ||
	   [[ $libcsfml == "y" ]] || [[ $libcsfml == "yes" ]];
    then
	if [[ $lib == "on" ]];
	then
	    echo -e "LDFLAGS\t\t+=\t-lc_graph_prog_full" >> Makefile
	else
	    echo -e "LDFLAGS\t\t=\t-lc_graph_prog_full" >> Makefile
	fi
	lib="on"
    fi
}

add_flags()
{
    echo -e "CFLAGS\t\t=\t-W -Wall -Wextra -Werror -Wshadow -Wunreachable-code -Wconversion -Wstrict-prototypes" >> Makefile
    echo -e "CFLAGS\t\t+=\t-Wswitch-default -Wswitch-enum" >> Makefile
    echo -e "CFLAGS\t\t+=\t-Wuninitialized -Winit-self" >> Makefile
    echo -e "CFLAGS\t\t+=\t-fstack-protector-strong" >> Makefile
    echo -e "CFLAGS\t\t+=\t-pedantic" >> Makefile

    if [[ $HOSTTYPE == $BITS32 ]];
    then
	echo -e "CFLAGS\t\t+=\t-Wdouble-promotion" >> Makefile
    fi

    echo "Are you compling for you own platform ? [o/platform]"
    read platform
    echo
    local platform=${platform,,}

    if [[ $platform == "yes" ]] || [[ $platform == "oui" ]] ||
	   [[ $platform == "y" ]] || [[ $platform == "o" ]];
    then
	echo -ne "CFLAGS\t\t+=\t-march=native" >> Makefile
    else
	echo -ne "CFLAGS\t\t+=\t-march=$platform" >> Makefile
    fi

    echo "Do you want to keep preprocessor and assembly file (.ii and .s) ?"
    read temp
    echo
    temp=${temp,,}

    if [[ $temp == "yes" ]] || [[ $temp == "oui" ]] ||
	   [[ $temp == "y" ]] || [[ $temp == "o" ]];
    then
	temp="on"
	echo " -save-temps" >> Makefile
    fi

    echo >> Makefile
}

make_n() {
    echo -e "CC\t\t=\tgcc" >> Makefile
    echo >> Makefile

    echo -e "RM\t\t=\trm -f" >> Makefile
    echo >> Makefile

    add_flags

    echo -e "CPPFLAGS\t=\t-I include" >> Makefile
    echo >> Makefile

    add_libmy
    add_libmath
    add_libcsfml
    if [[ $lib == "on" ]];
       then
	   echo >> Makefile
    fi

    echo -e "SRC_DIR\t\t=\tsrc" >> Makefile
    echo -e "SRC_FILES\t=\tmain.c\t\\" >> Makefile
    echo >> Makefile

    echo -e "SRCS\t\t=\t\$(addprefix \$(SRC_DIR)/, \$(SRC_FILES))" >> Makefile
    if [[ $temp == "on" ]];
    then
	echo -e "SRCS_NAME\t=\t\$(basename \$(SRCS))" >> Makefile
	echo -e "SRCS_TEMP\t=\t\$(notdir \$(SRCS_NAME).s \$(SRCS_NAME).i)" >> Makefile
    fi
    echo >> Makefile

    echo -e "OBJS\t\t=\t\$(SRCS:.c=.o)" >> Makefile
    echo >> Makefile

    echo "Binary Name"
    read bin_name
    echo

    echo -e "NAME\t\t=\t$bin_name" >> Makefile
    echo >> Makefile

    echo -e "all:\t\t\$(NAME)" >> Makefile
    echo >> Makefile

    echo -e "\$(NAME):\t\$(OBJS)" >> Makefile

    if [[ $lib == "on" ]];
    then
	echo -e "\t\t\$(CC) -o \$(NAME) \$(OBJS) \$(LDFLAGS)" >> Makefile
    else
	echo -e	"\t\t\$(CC) -o \$(NAME) \$(OBJS)" >> Makefile
    fi

    echo >> Makefile

    echo "clean:" >> Makefile
    echo -e "\t\t\$(RM) \$(OBJS)" >> Makefile
    if [[ $temp == "on" ]];
    then
	echo -e "\t\t\$(RM) \$(SRCS_TEMP)" >> Makefile
    fi
    echo >> Makefile

    echo -e "fclean:\t\tclean" >> Makefile
    echo -e "\t\t\$(RM) \$(NAME)" >> Makefile
    echo >> Makefile

    echo -e "re:\t\tfclean all" >> Makefile
    echo >> Makefile

    echo -e ".PHONY:\t\tall clean fclean re" >> Makefile
}

header()
{
    clear
    for i in $(eval echo "{1..$(tput cols)}"); do echo -n "T"; done
    echo
    echo
}

header

echo "##Press Ctrl+H then enter this file name and press enter" > Makefile
echo >> Makefile

make_n
