#!/bin/bash

############################
#			   #
# Made by Tiphaine LAURENT #
#			   #
############################

###### Actions ######

delete="-delete"
print="-print"

###### Options #######

option1=$1
option1=${option1,,}

option2=$2
option2=${option2,,}

######################

if [[ "$option1" == "-h" ]] || [[ "$option1" == "-hide" ]] ||
       [[ "$option2" == "-h" ]] || [[ "$option2" == "-hide" ]];
then
    unset print
fi
if [[ "$option1" == "-k" ]] || [[ "$option1" == "-keep" ]] ||
       [[ "$option2" == "-k" ]] || [[ "$option2" == "-keep" ]];
then
    unset delete
fi

find . -type f \( -name "*~" -o -name "#*#" \) -not -path '*\.emacs.d/backup*' $print $delete #-path ~/.emacs.d/backup -prune # Do not work with -delete

unset option1
unset option2
