#!/bin/bash

option=$1
option="${option,,}"

delete="-delete"
print="-print"

if [[ "$option" == "-h" ]] || [[ "$option" == "-hide" ]];
then
    unset print
elif [[ "$option" == "-k" ]] || [[ "$option" == "-keep" ]];
then
    unset delete
fi

find -type f \( -name "*~" -o -name "#*#" -o -name "*.o" \) $print $delete
