#!/bin/bash

############################
#			   #
# Made by Tiphaine LAURENT #
#			   #
############################

dir=$(dirname $1)
name=${1:1:$((${#1}-9))}

echo "Unarchiving $1 into $name at $dir"
tar -xzf $1
rm $1
